create table ACCOUNTS(ACCOUNT_ID INT, CONSTRAINT PK_ACCOUNTS PRIMARY KEY (ACCOUNT_ID));

create table TRANSFERS(TRANSFER_ID INT, DEBIT_ACCOUNT_ID INT, CREDIT_ACCOUNT_ID INT, MONEY DECIMAL, DATE DATETIME,
    CONSTRAINT PK_TRANSFERS PRIMARY KEY (TRANSFER_ID));